### ISSUE TITLE
endponts to move child by id

### ISSUE THREAD

**Issue by dennishoang** [Teamprojekt-Lagersystem/Lagersystem-Backend#46]
User should be able to move child (e.g. subStorages, Spaces, Prodcuts...) to another parent.

**Comment by lumeav** [comment]
If a storage has a space with products and I then move my storage to another storage, then two options appear:
-> Take all your substorages and spaces with you (should be implemented in #33)
-> Take all your spaces with you (because a space without a storageID should not exist)
-> Just move the storage and if you have spaces give your spaces to your parent/child

**Comment by Neoyx** [comment]
In general we provide a move method in storage, which moves the storage and all of its children. If the Frontend wants to move only one space/product of the storage, the moveSpace/moveProduct methods have to be called in the other repos.

**Comment by Neoyx** [comment]
![Image](https://github.com/user-attachments/assets/4b2809d1-9c55-4a88-afd0-a5ed1fece972)

**Comment by Neoyx** [comment]
**Note:** A substorage can be converted to a root storage by calling "moveStorage()" with specifing the parentId to be null. The request object would look like:
{
  "newParentId": null
} ==> for your information @Teamprojekt-Lagersystem/frontend
